### PR TITLE
Update LICENSE and NOTICE

### PR DESCRIPTION
**Pull request by kmcostel**
Hi Dave,

I got an email from Zak White saying we should update these 2 files, LICENSE and NOTICE.
I'm just trying to do that here. Please approve if you think it looks good.

Thanks,
Kevin

### CODE REVIEW

**Comment by dmcassel** [comment]
@kmcostel I'm no longer in a position to review policy docs. May I suggest @ryanjdew or @TrinhML?

**Comment by kmcostel** [comment]
Ok, thanks for the info, Dave. How can I get Ryan or Trinh to review and
accept the pull request? I think you have a power to approve pull requests?
Hope all is well.
- Kevin

**Comment by ryanjdew** [comment]
I don't appear to have write access to this repository, so GitHub won't allow me to accept the PR.

**Comment by TrinhML** [comment]
I'll fix that in a few. Handle?

On Mar 12, 2019 9:49 PM, Ryan Dew <notifications@github.com> wrote:

I don't appear to have write access to this repository, so GitHub won't allow me to accept the PR.

**Comment by ryanjdew** [comment]
ryanjdew

**Comment by TrinhML** [comment]
Should be all set, thank you!

**Review by ryanjdew — APPROVED** [review]

**Pull request merged**
